#!/usr/bin/env python3
"""Slim the precinct polygons into site/data/precincts.json.

Needed so a pin dropped on the map can be resolved to a precinct by
point-in-polygon, entirely in the browser. A dropped pin has no house number,
so the address index cannot answer it; the polygon layer can.

Covers all of Kent County: 202 precincts across 30 jurisdictions. This file
is loaded by every visitor whatever jurisdiction they are in, because it is
also what decides WHICH jurisdiction they are in -- the per-jurisdiction
address and street chunks are chosen from it. So it carries a jurisdictions
index: name, whether the place has wards, how many precincts, and a bounding
box to test against before any point-in-polygon runs.

No separate jurisdiction outline is needed. Precincts tile their jurisdiction
exactly, so their union IS the outline, and asking which precinct a point
falls in already answers which jurisdiction it is in.

The source file is site/data/precincts.geojson, regenerated by
refresh_precincts.py from the State of Michigan's precinct layer with its own
guards. This script only reshapes it, keeping the state's own identity fields
and rounding coordinates to ~1m.
"""
import json
import sys
from pathlib import Path
from provenance import provenance

# Paths are anchored to the repository root, one level up from this
# file, since these scripts live in scripts/ and write into site/data.
ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT / "site" / "data" / "precincts.geojson"
OUT = ROOT / "site" / "data" / "precincts.json"

EXPECTED_PRECINCTS = 202
EXPECTED_JURISDICTIONS = 30


def _point_in(lat, lng, rings):
    inside = False
    for ring in rings:
        n = len(ring)
        j = n - 1
        for i in range(n):
            xi, yi = ring[i][1], ring[i][0]      # rings are [lat, lng]
            xj, yj = ring[j][1], ring[j][0]
            if (yi > lat) != (yj > lat) and \
               lng < (xj - xi) * (lat - yi) / (yj - yi) + xi:
                inside = not inside
            j = i
    return inside


def _edge_dist(lat, lng, rings):
    """Rough distance from a point to the nearest boundary, in degrees."""
    best = float("inf")
    for ring in rings:
        for i in range(len(ring) - 1):
            ay, ax = ring[i][0], ring[i][1]
            by, bx = ring[i + 1][0], ring[i + 1][1]
            dx, dy = bx - ax, by - ay
            L = dx * dx + dy * dy
            t = 0 if L == 0 else max(0, min(1, ((lng - ax) * dx + (lat - ay) * dy) / L))
            cx, cy = ax + t * dx, ay + t * dy
            d = (lng - cx) ** 2 + (lat - cy) ** 2
            if d < best:
                best = d
    return best ** 0.5


def label_anchor(rings):
    """A point INSIDE the polygon to hang the precinct number on.

    The centroid is the obvious choice and it is wrong: several Grand Rapids
    precincts are concave enough that their centroid lands in a neighbouring
    precinct, which would put the wrong number on the wrong ground. This walks
    a grid over the polygon and keeps the interior point furthest from any
    boundary, so the number sits where there is room for it.
    """
    lats = [p[0] for r in rings for p in r]
    lngs = [p[1] for r in rings for p in r]
    lo_a, hi_a, lo_o, hi_o = min(lats), max(lats), min(lngs), max(lngs)
    best, best_d = None, -1.0
    STEPS = 24
    for i in range(1, STEPS):
        for j in range(1, STEPS):
            la = lo_a + (hi_a - lo_a) * i / STEPS
            lo = lo_o + (hi_o - lo_o) * j / STEPS
            if not _point_in(la, lo, rings):
                continue
            d = _edge_dist(la, lo, rings)
            if d > best_d:
                best_d, best = d, [round(la, 6), round(lo, 6)]
    if best is None:                       # degenerate: fall back to centroid
        best = [round(sum(lats) / len(lats), 6), round(sum(lngs) / len(lngs), 6)]
    return best


def build_index(precincts):
    """The jurisdictions index: what the page reads to decide which chunk of
    addresses and streets to load, before it has parsed a single one.

    A bounding box is enough to narrow 30 jurisdictions to one or two
    candidates, and point-in-polygon over just those settles it. Sorted by
    name so the file is stable between runs.

    The name is the state's JurisdictionName rather than anything derived from
    the precinct labels: "Bowne Twp 1" is the only precinct in Bowne Township,
    so there is nothing to derive a jurisdiction name from there.
    """
    by_mcd = {}
    for p in precincts:
        j = by_mcd.setdefault(p["mcd"], {
            "mcd": p["mcd"], "name": p["jurisdiction"], "wards": False,
            "precincts": 0, "bbox": [90.0, 180.0, -90.0, -180.0],
        })
        j["precincts"] += 1
        if p["ward"] is not None:
            j["wards"] = True
        box = j["bbox"]
        for ring in p["rings"]:
            for lat, lng in ring:
                box[0] = min(box[0], lat)
                box[1] = min(box[1], lng)
                box[2] = max(box[2], lat)
                box[3] = max(box[3], lng)

    for j in by_mcd.values():
        j["bbox"] = [round(v, 5) for v in j["bbox"]]
    return sorted(by_mcd.values(), key=lambda j: j["name"])


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src.exists():
        sys.exit(f"REFUSE: {src} not found; pass the path to the "
                 "precincts.geojson")
    d = json.loads(src.read_text())
    feats = d.get("features", [])
    if len(feats) != EXPECTED_PRECINCTS:
        sys.exit(f"REFUSE: expected {EXPECTED_PRECINCTS} precincts, got {len(feats)}")
    out = []
    for f in feats:
        p = f["properties"]
        g = f["geometry"]
        rings = g["coordinates"] if g["type"] == "Polygon" else \
            [r for poly in g["coordinates"] for r in poly]
        slim = [[[round(pt[1], 5), round(pt[0], 5)] for pt in ring]
                for ring in rings]
        out.append({
            # The state's own identity, carried through rather than rebuilt:
            # code is unique, name is already how the page wants to print it.
            "code": p["code"],
            "mcd": p["mcd"],
            "jurisdiction": p["jurisdiction"],
            "ward": p["ward"],            # null where the place has no wards
            "precinct": p["precinct"],
            "name": p["name"],
            # [lat, lng] to match every other file this site ships
            "rings": slim,
            "label": label_anchor(slim),
        })

    jurisdictions = build_index(out)
    if len(jurisdictions) != EXPECTED_JURISDICTIONS:
        sys.exit(f"REFUSE: expected {EXPECTED_JURISDICTIONS} jurisdictions, "
                 f"got {len(jurisdictions)}")
    OUT.write_text(json.dumps({
        "meta": {"source": "State of Michigan voting precinct layer, "
                           "via vote-gr", "count": len(out),
                 "jurisdictions": len(jurisdictions)},
        # Carried through from the fetch: pairs the state layer draws over the
        # same ground, so a lookup landing inside one can say it has no single
        # answer instead of picking.
        "known_overlaps": (d.get("provenance") or {}).get("known_overlaps", []),
        "jurisdictions": jurisdictions,
        "provenance": provenance(
            source="State of Michigan, Secretary of State voting precinct "
                   "layer. Slimmed from site/data/precincts.geojson, which "
                   "carries the full provenance for the fetch itself.",
            source_url="site/data/precincts.geojson",
            licence="Public record of the State of Michigan, redistributed as published.",
            made_by="build_precincts.py",
            how_to_update="Run refresh_precincts.py first, then "
                          "build_precincts.py. This script only reshapes; it "
                          "never fetches.",
            derived_from="precincts.geojson"),
        "precincts": out,
    }, separators=(",", ":")))
    print(f"wrote {len(out)} precincts across {len(jurisdictions)} "
          f"jurisdictions -> {OUT} ({OUT.stat().st_size/1024:.0f} KB)")
    for j in jurisdictions[:5]:
        print(f"  {j['precincts']:>3} precincts  {j['name']}"
              f"{'  (wards)' if j['wards'] else ''}")
    print(f"  ... {len(jurisdictions) - 5} more")


if __name__ == "__main__":
    main()
