#!/usr/bin/env python3
# Released into the public domain under the Unlicense, see UNLICENSE.
"""Slim the precinct polygons into site/data/precincts.json.

Needed so a pin dropped on the map can be resolved to a precinct by
point-in-polygon, entirely in the browser. A dropped pin has no house number,
so the address index cannot answer it; the polygon layer can.

Covers all of Kent County: 202 precincts across 30 jurisdictions. This file
is loaded by every visitor whatever jurisdiction they are in, because it is
also what decides WHICH jurisdiction they are in -- the per-jurisdiction
address and street chunks are chosen from it. So it carries a jurisdictions
index: name, whether the place has wards, how many precincts, and a bounding
box to test against before any point-in-polygon runs.

Precincts tile their jurisdiction exactly, so their union IS its outline, and
this computes that union once here rather than leaving the browser to infer it.
The page used to derive the outline by counting each precinct edge and keeping
the ones seen only once, which assumes neighbouring precincts share their
vertices exactly. They do not: refresh_precincts.py thins each polygon on its
own, so the two sides of a shared border keep different vertices off the same
line, neither edge matches, and both get drawn. That put 259 km of stray line
across the county, 71 km of it inside Grand Rapids alone.

The source file is site/data/precincts.geojson, regenerated by
refresh_precincts.py from the State of Michigan's precinct layer with its own
guards. This script only reshapes it, keeping the state's own identity fields
and rounding coordinates to ~1m.
"""
import json
import math
import sys
from pathlib import Path

from shapely.geometry import Polygon
from shapely.ops import transform, unary_union

from provenance import provenance

# Paths are anchored to the repository root, one level up from this
# file, since these scripts live in scripts/ and write into site/data.
ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT / "site" / "data" / "precincts.geojson"
OUT = ROOT / "site" / "data" / "precincts.json"

EXPECTED_PRECINCTS = 202
EXPECTED_JURISDICTIONS = 30

# Square metres per square degree at 43N, so the thresholds below can be
# reasoned about as ground rather than as coordinates.
M2_PER_DEG2 = 111320 * (111320 * 0.7314)

# A piece of the union smaller than this is digitizing noise, not ground
# anybody votes on. Matches SLIVER_M2 in refresh_precincts.py, which calls the
# same size an overlap not worth reporting. Nothing in Kent County is dropped
# by it today: the smallest real piece is Solon Township's 3,984 m2.
SPECK_M2 = 100

# An interior ring smaller than this is the gap between two precincts drawn to
# the same border, not an enclave. Every one of the county's 136 interior
# rings is under 1,500 m2 and all of them are dropped; a city genuinely
# surrounded by a township would be orders of magnitude larger and would
# survive, which is why this is a threshold rather than "discard all holes".
ENCLAVE_M2 = 5000

# Where two precincts describe their shared border differently, the union
# keeps the hairline between the two versions. Inside the jurisdiction that is
# an interior ring and ENCLAVE_M2 discards it. Where the same hairline reaches
# the outer border it is not a ring at all, it is a slot cut into the outline,
# and no area threshold can see it: Courtland Township had one 1.2 km deep.
#
# A close (dilate, then erode by the same amount) fills anything narrower than
# twice this and leaves everything else alone. Mitred joins rather than round
# ones because a round join would replace every corner of the county with an
# arc of new points. Measured over all thirty jurisdictions at 1.5 m: every
# slot closes, more than 99% of outline vertices do not move at all, and the
# furthest any of them moves is 0.35 m, which is a third of the ~1.1 m the
# coordinates are rounded to anyway. Raising it further heals nothing more.
CLOSE_M = 1.5


def _point_in(lat, lng, rings):
    inside = False
    for ring in rings:
        n = len(ring)
        j = n - 1
        for i in range(n):
            xi, yi = ring[i][1], ring[i][0]      # rings are [lat, lng]
            xj, yj = ring[j][1], ring[j][0]
            if (yi > lat) != (yj > lat) and \
               lng < (xj - xi) * (lat - yi) / (yj - yi) + xi:
                inside = not inside
            j = i
    return inside


def _edge_dist(lat, lng, rings):
    """Rough distance from a point to the nearest boundary, in degrees."""
    best = float("inf")
    for ring in rings:
        for i in range(len(ring) - 1):
            ay, ax = ring[i][0], ring[i][1]
            by, bx = ring[i + 1][0], ring[i + 1][1]
            dx, dy = bx - ax, by - ay
            L = dx * dx + dy * dy
            t = 0 if L == 0 else max(0, min(1, ((lng - ax) * dx + (lat - ay) * dy) / L))
            cx, cy = ax + t * dx, ay + t * dy
            d = (lng - cx) ** 2 + (lat - cy) ** 2
            if d < best:
                best = d
    return best ** 0.5


def label_anchor(rings):
    """A point INSIDE the polygon to hang the precinct number on.

    The centroid is the obvious choice and it is wrong: several Grand Rapids
    precincts are concave enough that their centroid lands in a neighbouring
    precinct, which would put the wrong number on the wrong ground. This walks
    a grid over the polygon and keeps the interior point furthest from any
    boundary, so the number sits where there is room for it.
    """
    lats = [p[0] for r in rings for p in r]
    lngs = [p[1] for r in rings for p in r]
    lo_a, hi_a, lo_o, hi_o = min(lats), max(lats), min(lngs), max(lngs)
    best, best_d = None, -1.0
    STEPS = 24
    for i in range(1, STEPS):
        for j in range(1, STEPS):
            la = lo_a + (hi_a - lo_a) * i / STEPS
            lo = lo_o + (hi_o - lo_o) * j / STEPS
            if not _point_in(la, lo, rings):
                continue
            d = _edge_dist(la, lo, rings)
            if d > best_d:
                best_d, best = d, [round(la, 6), round(lo, 6)]
    if best is None:                       # degenerate: fall back to centroid
        best = [round(sum(lats) / len(lats), 6), round(sum(lngs) / len(lngs), 6)]
    return best


def _close(geom, metres):
    """Fill slots narrower than 2 * metres, leaving the rest of the border be.

    Buffering happens in a space where a degree is the same distance in both
    directions, so the tolerance means metres on the ground rather than metres
    north and 0.73 of one east.
    """
    k = math.cos(math.radians(43.0))          # the county's latitude
    flat = transform(lambda x, y: (x * k, y), geom)
    eps = metres / 111320.0
    closed = flat.buffer(eps, join_style=2, mitre_limit=8.0) \
                 .buffer(-eps, join_style=2, mitre_limit=8.0)
    return transform(lambda x, y: (x / k, y), closed)


def _ring(coords):
    """One union ring in the shape the precinct rings already use.

    Rounded to the same 5 dp they carry, so the outline lands on the dashed
    precinct lines it bounds instead of a few centimetres off them, and
    closed the same way. Rounding can collapse neighbouring vertices onto
    each other, and a repeated point draws a dot under a round line cap, so
    consecutive duplicates go.
    """
    out = []
    for lng, lat in coords.coords:
        pt = [round(lat, 5), round(lng, 5)]
        if not out or out[-1] != pt:
            out.append(pt)
    if out[0] != out[-1]:
        out.append(list(out[0]))
    return out


def outline(precincts):
    """The jurisdiction's own border: the union of its precincts.

    Returns the rings to draw and a note of what was discarded, so a run says
    out loud when it throws something away rather than deciding quietly.

    A jurisdiction can be several separate pieces, and seven of the county's
    thirty are: Solon Township alone is in seven, because Cedar Springs sits
    inside it and is not clipped out. So every piece above SPECK_M2 is kept.
    """
    polys = []
    for p in precincts:
        for ring in p["rings"]:
            if len(ring) >= 4:
                polys.append(Polygon([(lng, lat) for lat, lng in ring]).buffer(0))
    if not polys:
        return [], {}

    union = _close(unary_union(polys), CLOSE_M)
    geoms = [union] if union.geom_type == "Polygon" else list(union.geoms)

    rings, specks, slivers, enclaves = [], [], [], []
    for g in sorted(geoms, key=lambda g: -g.area):
        area = g.area * M2_PER_DEG2
        if area < SPECK_M2:
            specks.append(round(area))
            continue
        rings.append(_ring(g.exterior))
        for h in g.interiors:
            hole = Polygon(h).area * M2_PER_DEG2
            if hole < ENCLAVE_M2:
                slivers.append(round(hole))
            else:
                enclaves.append(round(hole))
                rings.append(_ring(h))

    # A ring can round down to fewer than four points only if it was already
    # smaller than the rounding, which SPECK_M2 should have caught first.
    rings = [r for r in rings if len(r) >= 4]
    return rings, {"specks": specks, "slivers": slivers, "enclaves": enclaves}


def build_index(precincts):
    """The jurisdictions index: what the page reads to decide which chunk of
    addresses and streets to load, before it has parsed a single one.

    A bounding box is enough to narrow 30 jurisdictions to one or two
    candidates, and point-in-polygon over just those settles it. Sorted by
    name so the file is stable between runs.

    It also carries the jurisdiction's outline, which is the line the map
    draws to say "this is the city or township your address is in". See
    outline() for why that is computed here rather than in the browser.

    The name is the state's JurisdictionName rather than anything derived from
    the precinct labels: "Bowne Twp 1" is the only precinct in Bowne Township,
    so there is nothing to derive a jurisdiction name from there.
    """
    by_mcd, members = {}, {}
    for p in precincts:
        j = by_mcd.setdefault(p["mcd"], {
            "mcd": p["mcd"], "name": p["jurisdiction"], "wards": False,
            "precincts": 0, "bbox": [90.0, 180.0, -90.0, -180.0],
        })
        members.setdefault(p["mcd"], []).append(p)
        j["precincts"] += 1
        if p["ward"] is not None:
            j["wards"] = True
        box = j["bbox"]
        for ring in p["rings"]:
            for lat, lng in ring:
                box[0] = min(box[0], lat)
                box[1] = min(box[1], lng)
                box[2] = max(box[2], lat)
                box[3] = max(box[3], lng)

    for j in by_mcd.values():
        j["bbox"] = [round(v, 5) for v in j["bbox"]]
        rings, note = outline(members[j["mcd"]])
        if not rings:
            sys.exit(f"REFUSE: {j['name']} has no outline; its precincts did "
                     "not union into anything drawable")
        j["outline"] = rings
        for kind, sizes in sorted(note.items()):
            if kind == "slivers" or not sizes:
                continue
            print(f"  {j['name']}: {len(sizes)} {kind} "
                  f"{'kept' if kind == 'enclaves' else 'dropped'}, "
                  f"largest {max(sizes):,} m2")
    return sorted(by_mcd.values(), key=lambda j: j["name"])


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src.exists():
        sys.exit(f"REFUSE: {src} not found; pass the path to the "
                 "precincts.geojson")
    d = json.loads(src.read_text())
    feats = d.get("features", [])
    if len(feats) != EXPECTED_PRECINCTS:
        sys.exit(f"REFUSE: expected {EXPECTED_PRECINCTS} precincts, got {len(feats)}")
    out = []
    for f in feats:
        p = f["properties"]
        g = f["geometry"]
        rings = g["coordinates"] if g["type"] == "Polygon" else \
            [r for poly in g["coordinates"] for r in poly]
        slim = [[[round(pt[1], 5), round(pt[0], 5)] for pt in ring]
                for ring in rings]
        out.append({
            # The state's own identity, carried through rather than rebuilt:
            # code is unique, name is already how the page wants to print it.
            "code": p["code"],
            "mcd": p["mcd"],
            "jurisdiction": p["jurisdiction"],
            "ward": p["ward"],            # null where the place has no wards
            "precinct": p["precinct"],
            "name": p["name"],
            # [lat, lng] to match every other file this site ships
            "rings": slim,
            "label": label_anchor(slim),
        })

    jurisdictions = build_index(out)
    if len(jurisdictions) != EXPECTED_JURISDICTIONS:
        sys.exit(f"REFUSE: expected {EXPECTED_JURISDICTIONS} jurisdictions, "
                 f"got {len(jurisdictions)}")
    OUT.write_text(json.dumps({
        "meta": {"source": "State of Michigan voting precinct layer, "
                           "via vote-gr", "count": len(out),
                 "jurisdictions": len(jurisdictions)},
        # Carried through from the fetch: pairs the state layer draws over the
        # same ground, so a lookup landing inside one can say it has no single
        # answer instead of picking.
        "known_overlaps": (d.get("provenance") or {}).get("known_overlaps", []),
        "jurisdictions": jurisdictions,
        "provenance": provenance(
            source="State of Michigan, Secretary of State voting precinct "
                   "layer. Slimmed from site/data/precincts.geojson, which "
                   "carries the full provenance for the fetch itself.",
            source_url="site/data/precincts.geojson",
            licence="Public record of the State of Michigan, redistributed as published.",
            made_by="build_precincts.py",
            how_to_update="Run refresh_precincts.py first, then "
                          "build_precincts.py. This script only reshapes; it "
                          "never fetches.",
            derived_from="precincts.geojson"),
        "precincts": out,
    }, separators=(",", ":")))
    rings = sum(len(j["outline"]) for j in jurisdictions)
    points = sum(len(r) for j in jurisdictions for r in j["outline"])
    print(f"wrote {len(out)} precincts across {len(jurisdictions)} "
          f"jurisdictions -> {OUT} ({OUT.stat().st_size/1024:.0f} KB)")
    print(f"  outlines: {rings} rings, {points:,} points")
    for j in jurisdictions[:5]:
        print(f"  {j['precincts']:>3} precincts  {j['name']}"
              f"{'  (wards)' if j['wards'] else ''}")
    print(f"  ... {len(jurisdictions) - 5} more")


if __name__ == "__main__":
    main()
