#!/usr/bin/env python3
"""Slim the precinct polygons into site/data/precincts.json.

Needed so a pin dropped on the map can be resolved to a precinct by
point-in-polygon, entirely in the browser. A dropped pin has no house number,
so the address index cannot answer it; the polygon layer can.

The source file is site/data/precincts.geojson, regenerated by
refresh_precincts.py from the State of Michigan's precinct layer with its own
guards. This script only reshapes it, keeping ward and precinct properties and
rounding coordinates to ~1m.
"""
import json
import sys
from pathlib import Path
from provenance import provenance

# Paths are anchored to the repository root, one level up from this
# file, since these scripts live in scripts/ and write into site/data.
ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT / "site" / "data" / "precincts.geojson"
OUT = ROOT / "site" / "data" / "precincts.json"


def _point_in(lat, lng, rings):
    inside = False
    for ring in rings:
        n = len(ring)
        j = n - 1
        for i in range(n):
            xi, yi = ring[i][1], ring[i][0]      # rings are [lat, lng]
            xj, yj = ring[j][1], ring[j][0]
            if (yi > lat) != (yj > lat) and \
               lng < (xj - xi) * (lat - yi) / (yj - yi) + xi:
                inside = not inside
            j = i
    return inside


def _edge_dist(lat, lng, rings):
    """Rough distance from a point to the nearest boundary, in degrees."""
    best = float("inf")
    for ring in rings:
        for i in range(len(ring) - 1):
            ay, ax = ring[i][0], ring[i][1]
            by, bx = ring[i + 1][0], ring[i + 1][1]
            dx, dy = bx - ax, by - ay
            L = dx * dx + dy * dy
            t = 0 if L == 0 else max(0, min(1, ((lng - ax) * dx + (lat - ay) * dy) / L))
            cx, cy = ax + t * dx, ay + t * dy
            d = (lng - cx) ** 2 + (lat - cy) ** 2
            if d < best:
                best = d
    return best ** 0.5


def label_anchor(rings):
    """A point INSIDE the polygon to hang the precinct number on.

    The centroid is the obvious choice and it is wrong: several Grand Rapids
    precincts are concave enough that their centroid lands in a neighbouring
    precinct, which would put the wrong number on the wrong ground. This walks
    a grid over the polygon and keeps the interior point furthest from any
    boundary, so the number sits where there is room for it.
    """
    lats = [p[0] for r in rings for p in r]
    lngs = [p[1] for r in rings for p in r]
    lo_a, hi_a, lo_o, hi_o = min(lats), max(lats), min(lngs), max(lngs)
    best, best_d = None, -1.0
    STEPS = 24
    for i in range(1, STEPS):
        for j in range(1, STEPS):
            la = lo_a + (hi_a - lo_a) * i / STEPS
            lo = lo_o + (hi_o - lo_o) * j / STEPS
            if not _point_in(la, lo, rings):
                continue
            d = _edge_dist(la, lo, rings)
            if d > best_d:
                best_d, best = d, [round(la, 6), round(lo, 6)]
    if best is None:                       # degenerate: fall back to centroid
        best = [round(sum(lats) / len(lats), 6), round(sum(lngs) / len(lngs), 6)]
    return best


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src.exists():
        sys.exit(f"REFUSE: {src} not found; pass the path to the "
                 "precincts.geojson")
    d = json.loads(src.read_text())
    feats = d.get("features", [])
    if len(feats) != 59:
        sys.exit(f"REFUSE: expected 59 precincts, got {len(feats)}")
    out = []
    for f in feats:
        p = f["properties"]
        g = f["geometry"]
        rings = g["coordinates"] if g["type"] == "Polygon" else \
            [r for poly in g["coordinates"] for r in poly]
        slim = [[[round(pt[1], 5), round(pt[0], 5)] for pt in ring]
                for ring in rings]
        out.append({
            "precinct": str(p["precinct"]),
            "ward": str(p["ward"]),
            # [lat, lng] to match every other file this site ships
            "rings": slim,
            "label": label_anchor(slim),
        })
    OUT.write_text(json.dumps({
        "meta": {"source": "State of Michigan voting precinct layer, "
                           "via vote-gr", "count": len(out)},
        "provenance": provenance(
            source="State of Michigan, Secretary of State voting precinct "
                   "layer. Slimmed from site/data/precincts.geojson, which "
                   "carries the full provenance for the fetch itself.",
            source_url="site/data/precincts.geojson",
            licence="Public record of the State of Michigan, redistributed as published.",
            made_by="build_precincts.py",
            how_to_update="Run refresh_precincts.py first, then "
                          "build_precincts.py. This script only reshapes; it "
                          "never fetches.",
            derived_from="precincts.geojson"),
        "precincts": out,
    }, separators=(",", ":")))
    print(f"wrote {len(out)} precincts -> {OUT} "
          f"({OUT.stat().st_size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
